### ISSUE TITLE
Failed to instantiate module mdo-angular-cryptography

### ISSUE THREAD

**Issue by shiruken1** [middleout/angular-cryptography#10]
Hello, and thank you for this project!

I would love to get your help on this. I've included plenty of modules into my project, so far, but when I install angular-cryptography, I keep getting:

```
[$injector:nomod] Module 'ngMaterial' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
```

Here's my main file:
```
	angular.module('app',
	[
		'app.controllers',
		'app.filters',
		'app.services',
		'app.directives',
		'app.routes',
		'app.config',
		'partialsModule'
	]);

	angular.module('app.routes', []);
	angular.module('app.controllers', [ 
										'ngStorage',
										'ui.router',
										'satellizer',
										'ngMaterial',
										'restangular',
										'dtrw.bcrypt',
										'md.data.table',
										'angular-loading-bar',
										'pascalprecht.translate',
										'mdo-angular-cryptography'
									  ]);
```

If I uninstall angular-cryptography, and uncomment it from the list, everything goes back to normal. Any ideas would be highly appreciated.

Cheers!

**Comment by robinj** [comment]
How are you loading the javascript files into your page? I can't think of a reason why this module would prevent others from loading.

**Comment by davidcadena3** [comment]
I have the same problem. Any idea?

**Comment by shiruken1** [comment]
@robinj I'm loading them via an Elixir script that compiles all bower.json entries into a single app.js. I'm using (this boilerplate)[https://github.com/jadjoubran/laravel5-angular-material-starter/]

**Comment by shiruken1** [comment]
I figured out why, @davidcadena3. I installed through bower and tried getting crytojslib to run on its own, but it won't. It takes down the setup. I've included it from google's CDN, and removed it from the bower.json's dependencies. 

Magically ... it now works.
