### ISSUE TITLE
wiredep and the cryptojslib dependency

### ISSUE THREAD

**Issue by seyDoggy** [middleout/angular-cryptography#5]
While this isn't necessarily your issue, it's worth mentioning here. You include cryptojslib as a dependency in the bower file, which seems reasonable, however the main property in cryptojslib's bower file points to `**/*.js`. Wire dep happily parses this and adds...
 
```html
<script src="bower_components/cryptojslib/**/*.js"></script>
```

...to your html file without error. cryptojslib shouldn't reasonably include any main property at all given the nature of the library, and by that token you shouldn't include this library as a dependency.

Instead, I'd suggest rolling your cryptojs own fork that includes only the rollup you want to use here in your package and list that as a dependency instead. Then you can have it's main property pointed at the one file you need here.

**Comment by andreigabreanu** [comment]
I agree with your point. I'll leave this ticket open since I don't have the time right now to fix this and will review in the future (since its not really a bug/issue more of a "maintainable" thing).
